#!/bin/bash

git checkout master
git pull
git checkout server
git merge master
bundle install --deployment
if [$2 -eq "assets" ]; then
  bundle exec rake assets:precompile RAILS_ENV=production
else
  echo "not compiling assets"
fi
./script/thin_restart
tail -f log/production.log